#!/bin/bash

if [ $# != 1 ]; then 
	echo -e "usage: $0 INDEX"
	exit 1
fi
index=$1

regex_index="index: ([0-9]+)"
regex_binary="application.process.binary = \"(.*?)\""
search_binary=false
found=false

while read line; do
	if [ $search_binary = true ]; then
		if [[ $line =~ $regex_binary ]]; then
			if [ $found == true ]; then
				echo "${BASH_REMATCH[1]}"
				exit 0
			fi 
			search_binary=false
		fi 
	else
		if [[ $line =~ $regex_index ]]; then
			current_index="${BASH_REMATCH[1]}"
			if [ $index == $current_index ]; then 
				found=true
			fi
			search_binary=true
		fi
	fi
done < <(pacmd list-sink-inputs)

echo "No sink found with the given INDEX"
exit 2
